// Code generated by ogen, DO NOT EDIT.

package players

// OperationName is the ogen operation name
type OperationName = string

const (
	CreatePlayerOperation  OperationName = "CreatePlayer"
	DeletePlayerOperation  OperationName = "DeletePlayer"
	GetPlayerByIdOperation OperationName = "GetPlayerById"
	GetPlayersOperation    OperationName = "GetPlayers"
	PatchPlayerOperation   OperationName = "PatchPlayer"
	UpdatePlayerOperation  OperationName = "UpdatePlayer"
)
