// Code generated by ogen, DO NOT EDIT.

package playersapi

// DeletePlayerParams is parameters of deletePlayer operation.
type DeletePlayerParams struct {
	// Числовой идентификатор игрока.
	ID int
}

// GetPlayerByIdParams is parameters of getPlayerById operation.
type GetPlayerByIdParams struct {
	// Числовой идентификатор игрока.
	ID int
}

// PatchPlayerParams is parameters of patchPlayer operation.
type PatchPlayerParams struct {
	// Числовой идентификатор игрока.
	ID int
}

// UpdatePlayerParams is parameters of updatePlayer operation.
type UpdatePlayerParams struct {
	// Числовой идентификатор игрока.
	ID int
}
