// Code generated by ogen, DO NOT EDIT.
package playersapi

type CreatePlayerRes interface {
	createPlayerRes()
}

type DeletePlayerRes interface {
	deletePlayerRes()
}

type GetPlayerByIdRes interface {
	getPlayerByIdRes()
}

type PatchPlayerRes interface {
	patchPlayerRes()
}

type UpdatePlayerRes interface {
	updatePlayerRes()
}
