// Code generated by ogen, DO NOT EDIT.

package playersapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreatePlayer implements createPlayer operation.
//
// Создает одного игроков.
//
// Только одного.
//
// POST /players
func (UnimplementedHandler) CreatePlayer(ctx context.Context, req *PlayerInput) (r CreatePlayerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeletePlayer implements deletePlayer operation.
//
// Удалить игрока.
//
// DELETE /players/{id}
func (UnimplementedHandler) DeletePlayer(ctx context.Context, params DeletePlayerParams) (r DeletePlayerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPlayerById implements getPlayerById operation.
//
// Если игрок не существует - его нельзя получить.
//
// GET /players/{id}
func (UnimplementedHandler) GetPlayerById(ctx context.Context, params GetPlayerByIdParams) (r GetPlayerByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPlayers implements getPlayers operation.
//
// Возвращает список игроков.
//
// Порядок может быть любым.
//
// GET /players
func (UnimplementedHandler) GetPlayers(ctx context.Context) (r []Player, _ error) {
	return r, ht.ErrNotImplemented
}

// PatchPlayer implements patchPlayer operation.
//
// Частичное обновление игрока (можно изменить одно или
// оба поля).
//
// PATCH /players/{id}
func (UnimplementedHandler) PatchPlayer(ctx context.Context, req *PlayerPartial, params PatchPlayerParams) (r PatchPlayerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePlayer implements updatePlayer operation.
//
// Полное обновление игрока (замена всех полей, кроме id).
//
// PUT /players/{id}
func (UnimplementedHandler) UpdatePlayer(ctx context.Context, req *PlayerInput, params UpdatePlayerParams) (r UpdatePlayerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
