// Code generated by ogen, DO NOT EDIT.

package playersapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreatePlayer implements createPlayer operation.
	//
	// Создать нового игрока.
	//
	// POST /players
	CreatePlayer(ctx context.Context, req *PlayerInput) (CreatePlayerRes, error)
	// DeletePlayer implements deletePlayer operation.
	//
	// Удалить игрока.
	//
	// DELETE /players/{id}
	DeletePlayer(ctx context.Context, params DeletePlayerParams) (DeletePlayerRes, error)
	// GetPlayerById implements getPlayerById operation.
	//
	// Получить игрока по идентификатору.
	//
	// GET /players/{id}
	GetPlayerById(ctx context.Context, params GetPlayerByIdParams) (GetPlayerByIdRes, error)
	// GetPlayers implements getPlayers operation.
	//
	// Получить список всех игроков.
	//
	// GET /players
	GetPlayers(ctx context.Context) ([]Player, error)
	// PatchPlayer implements patchPlayer operation.
	//
	// Частичное обновление игрока (можно изменить одно или
	// оба поля).
	//
	// PATCH /players/{id}
	PatchPlayer(ctx context.Context, req *PlayerPartial, params PatchPlayerParams) (PatchPlayerRes, error)
	// UpdatePlayer implements updatePlayer operation.
	//
	// Полное обновление игрока (замена всех полей, кроме id).
	//
	// PUT /players/{id}
	UpdatePlayer(ctx context.Context, req *PlayerInput, params UpdatePlayerParams) (UpdatePlayerRes, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
