// Code generated by ogen, DO NOT EDIT.

package playersapi

import (
	"fmt"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// DeletePlayerNoContent is response for DeletePlayer operation.
type DeletePlayerNoContent struct{}

func (*DeletePlayerNoContent) deletePlayerRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	// Код ошибки (HTTP-статус или внутренний код).
	Code int `json:"code"`
	// Человекочитаемое описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

func (*Error) createPlayerRes()  {}
func (*Error) deletePlayerRes()  {}
func (*Error) getPlayerByIdRes() {}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type PatchPlayerBadRequest Error

func (*PatchPlayerBadRequest) patchPlayerRes() {}

type PatchPlayerNotFound Error

func (*PatchPlayerNotFound) patchPlayerRes() {}

// Ref: #/components/schemas/Player
type Player struct {
	// Уникальный идентификатор игрока.
	ID int `json:"id"`
	// Имя игрока.
	Name string `json:"name"`
	// Количество очков игрока (может быть дробным).
	Score float64 `json:"score"`
}

// GetID returns the value of ID.
func (s *Player) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *Player) GetName() string {
	return s.Name
}

// GetScore returns the value of Score.
func (s *Player) GetScore() float64 {
	return s.Score
}

// SetID sets the value of ID.
func (s *Player) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Player) SetName(val string) {
	s.Name = val
}

// SetScore sets the value of Score.
func (s *Player) SetScore(val float64) {
	s.Score = val
}

func (*Player) createPlayerRes()  {}
func (*Player) getPlayerByIdRes() {}
func (*Player) patchPlayerRes()   {}
func (*Player) updatePlayerRes()  {}

// Ref: #/components/schemas/PlayerInput
type PlayerInput struct {
	// Имя игрока (обязательно).
	Name string `json:"name"`
	// Количество очков (обязательно).
	Score float64 `json:"score"`
}

// GetName returns the value of Name.
func (s *PlayerInput) GetName() string {
	return s.Name
}

// GetScore returns the value of Score.
func (s *PlayerInput) GetScore() float64 {
	return s.Score
}

// SetName sets the value of Name.
func (s *PlayerInput) SetName(val string) {
	s.Name = val
}

// SetScore sets the value of Score.
func (s *PlayerInput) SetScore(val float64) {
	s.Score = val
}

// Ref: #/components/schemas/PlayerPartial
type PlayerPartial struct {
	// Имя игрока (опционально).
	Name OptString `json:"name"`
	// Количество очков (опционально).
	Score OptFloat64 `json:"score"`
}

// GetName returns the value of Name.
func (s *PlayerPartial) GetName() OptString {
	return s.Name
}

// GetScore returns the value of Score.
func (s *PlayerPartial) GetScore() OptFloat64 {
	return s.Score
}

// SetName sets the value of Name.
func (s *PlayerPartial) SetName(val OptString) {
	s.Name = val
}

// SetScore sets the value of Score.
func (s *PlayerPartial) SetScore(val OptFloat64) {
	s.Score = val
}

type UpdatePlayerBadRequest Error

func (*UpdatePlayerBadRequest) updatePlayerRes() {}

type UpdatePlayerNotFound Error

func (*UpdatePlayerNotFound) updatePlayerRes() {}
