// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/J0hnLenin/ogen-example/server/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// PlayerStorage is an autogenerated mock type for the PlayerStorage type
type PlayerStorage struct {
	mock.Mock
}

// DeletePlayer provides a mock function with given fields: ctx, id
func (_m *PlayerStorage) DeletePlayer(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePlayer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPlayerByID provides a mock function with given fields: ctx, id
func (_m *PlayerStorage) GetPlayerByID(ctx context.Context, id int) (*models.Player, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPlayerByID")
	}

	var r0 *models.Player
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.Player, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.Player); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Player)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlayers provides a mock function with given fields: ctx
func (_m *PlayerStorage) GetPlayers(ctx context.Context) ([]*models.Player, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPlayers")
	}

	var r0 []*models.Player
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Player, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Player); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Player)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertPlayer provides a mock function with given fields: ctx, player
func (_m *PlayerStorage) UpsertPlayer(ctx context.Context, player *models.Player) (*models.Player, error) {
	ret := _m.Called(ctx, player)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPlayer")
	}

	var r0 *models.Player
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Player) (*models.Player, error)); ok {
		return rf(ctx, player)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Player) *models.Player); ok {
		r0 = rf(ctx, player)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Player)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Player) error); ok {
		r1 = rf(ctx, player)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPlayerStorage creates a new instance of PlayerStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlayerStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlayerStorage {
	mock := &PlayerStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
